### ISSUE TITLE
Этот скрипт ломает устройство

### ISSUE THREAD

**Issue by SaintAnd** [dzianismaroz/sd-port-proton#4]
Этот скрипт ломает устройство
После него пропадает ядро

```
error: file `/boot/vmlinuz-linux-neptune-61' not found.
error: you need to load the kernel first.

Press any key to continue...
  Failed to boot both default and fallback entries.
Press any key to continue...
```

Но не переживайте, после восстановления системы всё работает. Либо сделав и используя флешку восстановления стим дек.
    <details>
      <summary>Три фото подтверждения здесь под спойлером</summary>
![grub-menu](https://github.com/dzianismaroz/sd-port-proton/assets/68377697/6af0f7c2-2758-41d7-893e-e88a3f264a9f)

![error-vmlinuz](https://github.com/dzianismaroz/sd-port-proton/assets/68377697/4b929975-e945-4ef5-8cf8-63e15c972f63)

![grub-ls-boot](https://github.com/dzianismaroz/sd-port-proton/assets/68377697/c8113e2e-db76-46b7-b4a6-657d257ac8d2)
    </details>

**Comment by Castro-Fidel** [comment]
Товарищ @dzianismaroz вы проверяли сами скрипт установки после крайнего (вашего) обновления?
Как минимум: https://github.com/dzianismaroz/sd-port-proton/commit/16627e74569e5fab12c1ce177140aa23d931ab61#r138316733

**Comment by dzianismaroz** [comment]
genau. alles war schön

**Comment by dzianismaroz** [comment]
Dear sirs @Castro-Fidel . The latest release since now is fully based on your [patch](https://github.com/Castro-Fidel/sd-port-proton/commit/d96d0706cab60a1f5a3e666bfda8dd09e281598c)  proposed

**Comment by Castro-Fidel** [comment]
> Dear sirs @Castro-Fidel . The latest release since now is fully based on your [patch](https://github.com/Castro-Fidel/sd-port-proton/commit/d96d0706cab60a1f5a3e666bfda8dd09e281598c) proposed
 from [patch](https://github.com/Castro-Fidel/sd-port-proton/commit/d96d0706cab60a1f5a3e666bfda8dd09e281598c)
- pacman -Syu --noconfirm zenity &> /dev/null
+ pacman -S --noconfirm zenity-light

You cannot install zenity and zenity-light at once. They are in conflict with each other.

**Comment by Castro-Fidel** [comment]
But I doubt that there can be such problems because of zenity.

**Comment by dzianismaroz** [comment]
I got several anonymous users complaining about impossiblity to boot Steam OS after using installation script
 *(4 confirmed cases i know)*
Only what we found out - they used Steam OS v **3.5.5**.
 
Workaround was attached to documentation.

Anyway I got a postive feedback about dozens of successfull installations.

Hard to say is script may really impact on grub loader / kernel image presence,  but it may happen due to problems with **zenity-light  / zenity**.
And ( it seems ) it hapened only to this poor guy @SaintAnd .

**Comment by Castro-Fidel** [comment]
> I got several anonymous users complaining about impossiblity to boot Steam OS after using installation script _(4 confirmed cases i know)_ Only what we found out - they used Steam OS v **3.5.5**.
> 
> Workaround was attached to documentation.
> 
> Anyway I got a postive feedback about dozens of successfull installations.
> 
> Hard to say is script may really impact on grub loader / kernel image presence, but it may happen due to problems with **zenity-light / zenity**. And ( it seems ) it hapened only to this poor guy @SaintAnd .

Then make a close-up warning about this.
