### ISSUE TITLE
Auto Intall Genshin Impact Not Work

### ISSUE THREAD

**Issue by ToniBC** [dzianismaroz/sd-port-proton#5]
When we use the Self-install version of Genshin Impact, it starts, downloads the Launcher and runs it without problems.

Then, we can select the download path, in my case, the MicroSD (D:) and it installs without problems.

Afterwards PortProton launches the Launcher again to download the game and that is when it fails, since while in the launcher, in a few seconds, PortProton closes the Genshin Launcher. Even if you quickly click to download, the system closes the Launcher and does not let you install.

If you install it manually, it works without problems, but the automatic mode does not work well because it closes the launcher.

Thank you.

**Comment by dzianismaroz** [comment]
sorry, buddies, I suppose your problem is not linked to this bash script of this abandoned repository.

however the original maintainers of PortProton released its latest version with full support of SteamDeck and easy way of it's installation.
