### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by majkpe** [dzianismaroz/sd-port-proton#6]
It stuck when try to download this file...

![Zrzut ekranu 2024-06-21 161117](https://github.com/dzianismaroz/sd-port-proton/assets/173477783/22a31f37-1b66-4b4b-93a2-cd426d13df14)

**Comment by dzianismaroz** [comment]
sorry this installation method is no longer compatible with latest steam OS versions. Please use official installer by PortProton team
[check Flatpak hub](https://flathub.org/apps/ru.linux_gaming.PortProton)
